name: pro_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  hexagon: ^0.2.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/database/hadith_db.db
    - assets/images/
  fonts:
    - family: Kalpurush
      fonts:
        - asset: assets/fonts/Kalpurush.ttf
    - family: KFGQ
      fonts:
        - asset: assets/fonts/font_kfgq.ttf
